-- ==========================================
-- Fix: prospect_tasks
-- - Ensure prospect_id FK has ON DELETE CASCADE
-- - Ensure id is GENERATED BY DEFAULT AS IDENTITY (not ALWAYS)
-- Table is empty -> safe to DROP & recreate
-- ==========================================

BEGIN;

-- 0) Safety: drop trigger if it exists (avoid dependency issues)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'set_updated_at'
      AND tgrelid = 'public.prospect_tasks'::regclass
  ) THEN
    DROP TRIGGER set_updated_at ON public.prospect_tasks;
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    NULL;
END$$;

-- 1) Drop indexes (if any)
DROP INDEX IF EXISTS public.idx_prospect_tasks_status_date;
DROP INDEX IF EXISTS public.idx_prospect_tasks_prospect;
DROP INDEX IF EXISTS public.idx_prospect_tasks_date_priority;

-- 2) Drop table (empty)
DROP TABLE IF EXISTS public.prospect_tasks;

-- 3) Recreate table with correct identity + ON DELETE CASCADE
CREATE TABLE public.prospect_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  prospect_id uuid NOT NULL
    REFERENCES public.prospects(id) ON DELETE CASCADE,

  task_date date NOT NULL,

  priority public.task_priority_enum NOT NULL DEFAULT 'MEDIUM',

  note text,

  status public.reminder_status_enum NOT NULL DEFAULT 'PLANNED',

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id),
  completed_at timestamptz,

  reschedule_count integer NOT NULL DEFAULT 0
);

-- 4) Recreate trigger updated_at (same pattern as prospect_reminders)
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.prospect_tasks
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- 5) Recreate indexes
CREATE INDEX idx_prospect_tasks_status_date
  ON public.prospect_tasks (status, task_date);

CREATE INDEX idx_prospect_tasks_prospect
  ON public.prospect_tasks (prospect_id);

CREATE INDEX idx_prospect_tasks_date_priority
  ON public.prospect_tasks (task_date, priority, id);

COMMIT;